In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5])
np.isin(a, b)

array([ True, False,  True, False,  True])

In [5]:
isin = [False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True]
isin = np.array(isin, dtype=bool)


In [6]:
isin.sum()

128

In [11]:
isin[None, :] == isin[:, None]

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [24]:
import torch

def get_neighbors(a, neighbors):
    """
    a: B x L
    neighbors: B x L
    result: B x L x M
    """
    B, L = a.shape
    a = a[:, :, None].expand(-1, -1, L)  # Extend a to shape B x L x M
    result = a.gather(2, neighbors)
    return result

# 示例数据
a = torch.tensor([[0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0],
                  [0,0,0,0,0,0,0,0]])  # Shape (4, 8)

neighbors = torch.tensor([list(range(8)),
                          list(range(8)),
                          list(range(8)),
                          list(range(8))])  # Shape (4, 8)

# result = get_neighbors(a, neighbors)
# print(result)


In [25]:
B, L = a.shape
a = a[:, :, None].expand(-1, -1, L)  # Extend a to shape B x L x M
a.shape

torch.Size([4, 8, 8])

In [ ]:
a = a[:, :, None].expand(-1, -1, L)  # Extend a to shape B x L x M
a.shape

In [26]:

result = a.gather(1, neighbors)
result

RuntimeError: Index tensor must have the same number of dimensions as input tensor

In [10]:
neighbors

tensor([[0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7]])

In [19]:
import torch

# 定义一个示例张量 a
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

# 定义索引张量 index
index = torch.tensor([[0, 2],
                      [2, 0],
                      [1, 2],])

# 使用 gather 函数
result = a.gather(0, index)

print(result)


tensor([[1, 8],
        [7, 2],
        [4, 8]])
